### PR TITLE
ddns-scripts: remove route53

### PR DESCRIPTION
**Pull request by SPiskurskyi**
Removed route53 service provider. The reasons for removal are that the custom script uses the openssl binary, and that it does not work.

Reference: OWF-2783

### CODE REVIEW

**Comment by septimomend** [comment]
What if customer will need route53 service?

**Comment by SPiskurskyi** [comment]
> What if customer will need route53 service?

There is no route53 service in the requirements.

**Comment by septimomend** [comment]
> > What if customer will need route53 service?
> 
> There is no route53 service in the requirements.

Which requirements? And what if we will have this in requirements tomorrow? Removing something is the easiest way, but I don't think it is ok in this case. Maybe we should consider to use some alternative methods and keep route53 service available?

**Review by septimomend — CHANGES_REQUESTED** [review]
Disable CONFIG_PACKAGE_ddns-scripts-route53 instead of removing it here

**Comment by SPiskurskyi** [comment]
> Disable CONFIG_PACKAGE_ddns-scripts-route53 instead of removing it here

done by https://github.com/kn-gl/feed_prpl/pull/137/files, removing following line DEPENDS += +ddns-scripts_route53-v1

**Pull request closed without merging**
